### PR TITLE
Pr/hotfix 1.12.3

### PR DESCRIPTION
**Pull request by domideimel**
### Related Issues

closes #
#4612
#4637

### Short Description and Why It's Useful

Reduces Bundle size by changing the handling of Babel Polyfills

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by Fifciu — CHANGES_REQUESTED** [review]
Great job! But please update the changelog

**Comment by Fifciu** [comment]
I also see that unit tests are not passing

**Comment by domideimel** [comment]
> I also see that unit tests are not passing

Found the issue. It was the babel.config.js

**Comment by domideimel** [comment]
> I also see that unit tests are not passing

Found the Issue

**Review by Fifciu — APPROVED** [review]

**Comment by Fifciu** [comment]
Great job, thanks!

**Pull request merged**
