### PR TITLE
fix: development hot-reload speed webpack config

### LINKED ISSUE #5559: Webpack hot reload extremly slow on development
## Current behavior

The hot-reload config in development takes a lot even with good hardware, approximate 6 seconds for a change.

## Expected behavior

Should compile faster would say that average is > 2 seconds for most projects. 

## Steps to reproduce the issue

Download a theme, (currently using capybara) startup the project in development mode and make a change, wait for webpack hot-reload.

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
The root of the issue is webpack + ts-loader checking for errors while hot-reloading, by providing the optimization config that webpack suggest in their [docs](https://webpack.js.org/guides/build-performance/#typescript-loader) the compile time is extremly fast, compared with the current one. 

By providing `transpileOnly` it completly stops checking for type errors. Then adding the fork-ts-checker-webpack-plugin it will move the type checker to a separate process which will be inside your development environment and will not affect your compile times.

### PR DESCRIPTION
**Pull request by PawFV**
This is a bugfix for current stable version on https://demo.storefrontcloud.io

### Related issues

closes #5559

### Short description and why it's useful

The root of the issue is webpack + ts-loader checking for errors while hot-reloading, by providing the optimization config that webpack suggest in their [docs](https://webpack.js.org/guides/build-performance/#typescript-loader) the compile time is extremly fast, compared with the current one. 

By providing `transpileOnly` it completly stops checking for type errors. Then adding the fork-ts-checker-webpack-plugin it will move the type checker to a separate process which will be inside your development environment and will not affect your compile times.

### PR status check
This is hotfix PR, it means that it contain fix for current stable version. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] I've created this branch from `master` or `hotfix` branch
- [ ] I want to merge this PR into `hotfix` branch

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Comments:

as requested in #5560 by @Fifciu I rebased it to this current branch.

Notes: You might actually need to fix some type errors that will show in the project when building, as I had to in my current project. This are not really hard to fix errors, just type annotation/missing errors and only a few.

### CODE REVIEW

**Comment by lukaszjedrasik** [comment]
Looks great! But as you wrote: 
```
Notes: You might actually need to fix some type errors that will show in the project when building, as I had to in my current project. This are not really hard to fix errors, just type annotation/missing errors and only a few.```

We cannot approve these changes with any errors. Please fix it and PR will be merged :)

**Review by lukaszjedrasik — APPROVED** [review]

**Review by Fifciu — CHANGES_REQUESTED** [review]
Please update the Changelog

**Review by Fifciu — APPROVED** [review]

**Comment by Fifciu** [comment]
Thanks a lot for this one!

**Comment by Fifciu** [comment]
If you are going to use it in your project right now - please make sure to apply also this fix: https://github.com/vuestorefront/vue-storefront/pull/5813

**Pull request merged**
