### PR TITLE
Fix order category products by position

### LINKED ISSUE #3058: Category sort = 'position:asc' does not reflect the order set within magento categories
## Current behavior
Currently it does not seem possible to display products within categories using the order specified in the Magento admin. 

I am able to see the position number in the elastic data using Kibana. When using the new magento2-vsbridge-indexer you can see this in the categories attribute against a product. 

When using the mage2vuestorefront to import data, the position number is set on extension_attributes.category_links

In either case, setting sort = 'position:asc' or 'position:desc' makes no difference to the sorting of products.

## Expected behavior
When sort = 'position:asc' products within categories should be ordered as per the order field within magento admin

## Steps to reproduce the issue
Either using postman to hit the api directly or by configuring the storefront to sort products by position:asc products will not sort by the position number. And position:desc returns products in same position as position:asc. 

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle]
* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

### PR DESCRIPTION
**Pull request by rozzilla**
### Related Issues
closes #3058

### Short Description of the PR
Fix order category products by position, used for Magento 1 & 2.

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [x] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

### CODE REVIEW

**Comment by Fifciu** [comment]
Awesome one! However, please rebase it to the `develop`. We cannot merge it to the master branch.

**Comment by rozzilla** [comment]
Hey @Fifciu! Sorry for that, I didn't realize I was on the master branch.
Please, let me know if now it's ok. Otherwise, I'll delete this PR and redo this from scratch.

Thank you!

**Comment by lukaszjedrasik** [comment]
It works fine. Great job!

**Review by lukaszjedrasik — APPROVED** [review]

**Review by lukaszjedrasik — CHANGES_REQUESTED** [review]
It works fine. Great job!
Anyway please create a new PR related to the `develop` and it will be merged.

**Comment by rozzilla** [comment]
Hi @lukaszjedrasik, you can find it here: https://github.com/vuestorefront/vue-storefront/pull/5819

**Pull request closed without merging**
