### PR TITLE
Add optional config for shared user config (#5314)

### LINKED ISSUE #5314: Option for sharing user storage across stores in multistore
## What is the motivation for adding / enhancing this feature?
When using the multistore feature, there is a config option for `commonCache`, which will determine if local storage will store data per store or not. This is very useful for localization. However, sometimes the user data might not need to be stored separately per store.

For example, if using Magento 2 as the backend, you have the option to allow customer accounts to be shared across all websites and stores, or require customers to create a new account per website. We currently have our shop setup to share the user accounts across all websites in Magento.

This results in unnecessary duplication of storage for the user data. This also means a different customer token is created and stored per store in Vue Storefront, but in reality we only need one per user. We saw some strange behavior when switching stores as a logged-in user.

A simple solution to this could be to add a new option in the configuration, for example `storeViews.commonUserCache`. Then, in `core/modules/user/index.ts` we can change `StorageManager.init('user')` to `StorageManager.init('user', !config.storeViews.commonUserCache)`.

## What are the acceptance criteria 

* [ ] Can cache user data globally or per-store, independently from the `commonCache` configuration.

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

## Additional information

If there are better solutions for this please let me know. Otherwise I can work on this using the solution I suggested above.

### PR DESCRIPTION
**Pull request by rain2o**
### Related Issues

closes #5314 

### Short Description and Why It's Useful

Adds the ability to manage the configuration of User data being cached separately per store (in multistore setup) or not. As described in issue #5314 there can be a situation (with Magento 1 & 2 at least) where you can have separate catalog data per store, but users are shared across all stores.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by Fifciu — APPROVED** [review]

**Comment by Fifciu** [comment]
Good job, thanks!

**Review by Fifciu — CHANGES_REQUESTED** [review]
Let's make `commonCache` `array<string> | boolean`
For true/false, behaviour should be as it is.
For array, it should always check if the first argument of `StorageManager.init` is inside the array. If so, we use a common cache for this storage.

With this approach, our config won't grow that much and it will be easy to use commonCache for certain storages in the future

**Comment by rain2o** [comment]
@Fifciu Sorry, for some reason I only just now saw your requested changes. 
If we change `commonCache` to be `array<string> | boolean` how do you propose we handle that change in `StoreManager::init()`? Currently it looks like this:
```javascript
init: function (collectionName: string, isLocalized = !config.storeViews.commonCache, storageQuota = 0) {}
```
Without breaking current instances of VSF where that function is potentially called with the 2nd parameter, I can't think of a way to change this to account for a possible array. Normally I would say something like
```javascript
init: function (collectionName: string, storageQuota = 0) {
  const isLocalized = Array.isArray(config.storeViews.commonCache)
    ? config.storeViews.commonCache.indexOf(collectionName) === -1
    : !config.storeViews.commonCache;
  this.storageMap[collectionName] = _prepareCacheStorage(collectionName, isLocalized, storageQuota)
  return this.storageMap[collectionName]
}
```

But, to be backwards compatible we shouldn't remove the parameter, and I don't think complex logic like that can be used for a default param value (maybe I'm wrong?).

Any thoughts on how to safely implement this?

**Comment by bloodf** [comment]
This is closed due to inactivity.

If you want your PR to be re-opened, please update your files, check for any conflicts.

If your PR is for Vue Storefront 1 target the new repository at https://github.com/vuestorefront/vue-storefront-1

**Comment by rain2o** [comment]
@bloodf This ticket was inactive because I was waiting for some feedback from the vsf team. If someone will help me work through the issue I presented I'd be happy to update the MR.

**Pull request closed without merging**
