### PR TITLE
Fix checkout routing not respecting non-default locale

### LINKED ISSUE #5935: Checkout routing not respecting current locale
## Current behaviour
Routing through the checkout doesn't take locale into account. With the demo site, if you change to `de` and try to buy something, you don't get routed to the `de` version. This starts from the CartSidebar and goes all the way to the ThankYou page.

## Expected behaviour
Checkout routing keeps you fully in the current locale.

## Steps to reproduce the issue
- `npx @vue-storefront/cli init` (commercetools)
- `cd <dir>`
- `yarn`
- `yarn dev`
- change to `de`
- add product to cart
- open cart sidebar and "go to checkout" button doesn't include `de`
- all other back/forward links in the checkout also suffer the same thing all the way until the thank you page

## Version of Vue Storefront
- [ ] Vue Storefront 1
- [x] Vue Storefront 2 (next)

## Can you handle fixing this bug by yourself?
- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next/VSF2)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome  90.0.4430.212
- OS: Windows 10.0.19042 Build 19042
- Node: 14.16.1
- Code Version: next (53982be079460ca6f8830411e4c78ffe18afad79)

## Additional information
N/A

### PR DESCRIPTION
**Pull request by philipbushnell-valtech**
### Related Issues

closes #5935

### Short Description of the PR

Routing through the checkout wouldn't respect the locale when not using the default locale

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [x] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

### CODE REVIEW

**Comment by andrzejewsky** [comment]
@philipbushnell-valtech looks good - can you resolve the conflict?

**Comment by philipbushnell-valtech** [comment]
@andrzejewsky - conflict resolved for you.

**Comment by bloodf** [comment]
This is closed due to inactivity.

If you want your PR to be re-opened, please update your files, check for any conflicts.

If your PR is for Vue Storefront 1 target the new repository at https://github.com/vuestorefront/vue-storefront-1

**Comment by philipbushnell-valtech** [comment]
@andrzejewsky, @bloodf - how come this didn't get merged? Why did it sit unmerged for so long when it was good to go? I'm not going to waste time creating another PR so you may want to double check if this is still an issue and re-open this PR.

**Pull request closed without merging**
