### PR TITLE
Feature Improve docker

### LINKED ISSUE #2103: Improve the docker setup
## What are the acceptance criteria 
- Improve and fix the Docker setup by using muti-stage builds:
  - Use node-slim for building the application (we use native dependencies (node-sass) for example which requires Python and other dependencies)
  - Use node-alpine for running the app

- Explore #1845.

- Remove the shell script (not needed).

- Use a proper dev/prod setup.

# Can you complete this feature request by yourself?
YES

### PR DESCRIPTION
**Pull request by tonyisworking**
### Related Issues
closes #2103 - Improve the docker setup

### Short Description and Why It's Useful
- Faster Docker startup times 
- scale via containers instead of pm2 
- add source files into the image instead of bind mounting
- restructure docker build to be cacheable
- add docker healthcheck to app
- add nginx and sample nginx.conf to proxy to the app containers

Should be able to do a `docker-compose up -d --build --scale app=4` and it should bring up 4 app containers

### Which Environment This Relates To
- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`

### Upgrade Notes and Changelog
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by tonyisworking** [comment]
@pkarw What should it be named? `-alt`, `-next`, `new`?

**Comment by pkarw** [comment]
Hi @tonyisworking maybe “-alt”?

**Comment by pkarw** [comment]
@tonyisworking can you please fix the conflicts?

**Comment by bloodf** [comment]
This is closed due to inactivity.

If you want your PR to be re-opened, please update your files, check for any conflicts.

If your PR is for Vue Storefront 1 target the new repository at https://github.com/vuestorefront/vue-storefront-1

**Pull request closed without merging**
