### PR TITLE
useUser custom query support

### PR DESCRIPTION
**Pull request by vn-vlad**
### Related Issues
https://vsf.atlassian.net/browse/EN-180

### CODE REVIEW

**Review by andrzejewsky — CHANGES_REQUESTED** [review]
you haven't updated api-client for commercetools,  example: https://github.com/vuestorefront/vue-storefront/blob/next/packages/commercetools/api-client/src/api/getProduct/index.ts#L25-L27

**Comment by vn-vlad** [comment]
> you haven't updated api-client for commercetools, example: https://github.com/vuestorefront/vue-storefront/blob/next/packages/commercetools/api-client/src/api/getProduct/index.ts#L25-L27

CT api-client “getMe” method already supports customQuery, and only this method is used with the customQuery parameter in CT `useUser` composable.

**Comment by andrzejewsky** [comment]
@vn-vlad can you please resolve conflicts and i think we are ready to merge it
@igorwojciechowski please test this branch

**Review by andrzejewsky — APPROVED** [review]

**Comment by igorwojciechowski** [comment]
Performed regression tests - seems ok!

**Pull request merged**
