### PR TITLE
feat: remove helpers/filters from nuxt-theme and commercetools

### LINKED ISSUE #5620: Remove "helpers/filters"
`helpers/filters` can be removed from `@vue-storefront/nuxt-theme` and `@vue-storefront/commercetools-theme` because they are nto used anymore. The same functionality is provided by `useUiHelpers`.

## Version of Vue Storefront
- [ ] Vue Storefront
- [X] Vue Storefront Next

## Can you complete this feature request by yourself?
- [X] YES
- [ ] NO

### PR DESCRIPTION
**Pull request by porithe**
### Related Issues

closes #5620 

### Short Description of the PR
Removed `helpers/filters` from `@vue-storefront/nuxt-theme` and `@vue-storefront/commercetools-theme` because they are useless now.

### Pull Request Checklist
- [X] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [X] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [X] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [X] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

### CODE REVIEW

**Comment by porithe** [comment]
The documentation (next) has been already updated, so I think everything is good now. What about this error in deploy PR? @filipsobol

**Review by filipsobol — APPROVED** [review]

**Comment by filipsobol** [comment]
> The documentation (next) has been already updated, so I think everything is good now. What about this error in deploy PR? @filipsobol

Can you add a changelog, please? https://docs.vuestorefront.io/v2/contributing/creating-changelog.html

**Review by filipsobol — CHANGES_REQUESTED** [review]
> The documentation (next) has been already updated, so I think everything is good now. What about this error in deploy PR? @filipsobol

Can you add a changelog, please? https://docs.vuestorefront.io/v2/contributing/creating-changelog.html

**Review by filipsobol — APPROVED** [review]

**Comment by filrak** [comment]
Thanks, merging!

**Pull request merged**
