### PR TITLE
Add K8s production setup to docs

### PR DESCRIPTION
**Pull request by waynetheisinger**
### Related Issues
#2365

### Short Description and Why It's Useful
When completed it will give full instructions for a working production setup in Kubernetes

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Fifciu** [comment]
It looks truly amazing. Can't wait to see the whole doc, keep it up!

**Comment by waynetheisinger** [comment]
Hi @mkoszutowski I'm working on Kubernetes documentation - why do we have a dev/docker/Dockerfile that isn't being called by the docker-compose.yml 

Is it intended as a production docker template? And if it is why is in a directory called dev?
If it isn't what purpose does it have? Asking you cos you were the last person to touch it... thanks

**Comment by waynetheisinger** [comment]
Hi @pszreder or @pkarw - I am working on the Kubernetes documentation
In [PR 1332](https://github.com/DivanteLtd/vue-storefront/pull/1332) an Env was added `PM2_ARG` which starts PM2 process manager with the --no-deamon flag... only in a docker environment... 

I presume that Kubernetes also needs the --no-deamon flag as by docker we mean containers rather than purely docker? (If I'm correct I'll explain this in the documentation... i.e. I'm not asking for a name change... (2 hard things, blah blah)...

**Comment by mkoszutowski** [comment]
@waynetheisinger I will try to answer all your questions :)

The `/dev/docker/Dockerfile` is used to create demo sites.

Kubernetes needs  `--no-deamon` flag... Generally, Kubernetes use Docker in most cases. I'm not sure how other container engines works but we can assume `--no-deamon` is needed for all container solutions.

**Comment by waynetheisinger** [comment]
Hi @mkoszutowski I'm getting 

```
Error: Cannot find module '/var/www/start'
15:07:55 3|server   |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
15:07:55 3|server   |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
15:07:55 3|server   |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
15:07:55 3|server   |     at main (/var/www/node_modules/ts-node/src/bin.ts:227:14)
15:07:55 3|server   |     at Object.<anonymous> (/var/www/node_modules/ts-node/src/bin.ts:513:3)
15:07:55 3|server   |     at Module._compile (internal/modules/cjs/loader.js:778:30)
15:07:55 3|server   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
15:07:55 3|server   |     at Module.load (internal/modules/cjs/loader.js:653:32)
15:07:55 3|server   |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
15:07:55 3|server   |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

There are related issues saying that this is a config problem

1. https://github.com/DivanteLtd/vue-storefront/issues/4454#issuecomment-633978098
2. https://github.com/DivanteLtd/vue-storefront/issues/3981

Can you (or indeed anyone) check if any changes have been made to the config in the kubernetes build that is running the dev store.

Alternatively as per the second answer has the start command for pm2 been changed... 

In the meantime I will try both solutions - I've asked here before testing myself because I'd like to go with the 'official' solution that the core team uses rather than a community suggestion that might have unintended side effects (thinking of the config change here rather than the pm2 reset.)

**Comment by waynetheisinger** [comment]
Well I haven't had a reply but I can confirm that the config change at least works so I'm going with that regardless of whether it's the official solution.

**Comment by waynetheisinger** [comment]
Hi @mkoszutowski - I think this is ready for renew now, I've used it as the base for our production release so I can confirm that following it should work in production. In the end we decided to host our Elasticsearch on a VM rather than in K8s because the project was for an M1 store and the M1 bridge won't talk to ES7 so we had to tie it to ES5.6 but we got a working installation of ES7 in Kube and we are confident that the problem was compatibility and not that the ECK was failing in some way. (On that point I'm gonna do a quick edit to mention the M1 point, might save someone some time)

**Comment by waynetheisinger** [comment]
@Fifciu @mkoszutowski - any progress on getting this reviewed and merged?

**Comment by mkoszut** [comment]
@waynetheisinger Thanks for your effort! It is really great work! I will try to check it tomorrow or in the next week.

**Comment by mkoszut** [comment]
@waynetheisinger I suppose you spent a lot of time to prepare this documentation and it was really big effort for you to prepare it but I have a problem with this PR. It is great work but it isn't documentation. What do I mean? It looks more like blog post or article not a documentation page.

In documentation we shouldn't use phrases like belove but of cource we can in blog post or article

> However, I would advise that the most convenient registry is [Github Packages](https://docs.github.com/en/packages). Therefore, I use it in the examples below. (https://github.com/vuestorefront/vue-storefront/pull/4852/files#diff-f81ee7f9a2333ab4e0b0465487cef88a97be612231ecf30432a8f494174d8410R1008)

> Personally I like to have 2 slaves for an extra layer of redundancy. (https://github.com/vuestorefront/vue-storefront/pull/4852/files#diff-f81ee7f9a2333ab4e0b0465487cef88a97be612231ecf30432a8f494174d8410R719)

There is more similar phrases with your opinions.

Did you consider publishing it as a blog post or article, eg. [on Medium](https://medium.com/) we would link to your article our documentation.

**Comment by bloodf** [comment]
This is closed due to inactivity.

If you want your PR to be re-opened, please update your files, check for any conflicts.

If your PR is for Vue Storefront 1 target the new repository at https://github.com/vuestorefront/vue-storefront-1

**Pull request closed without merging**
