### PR TITLE
Solve problem of VS Code imports from .ts

### PR DESCRIPTION
**Pull request by rozzilla**
### Related Issues
#1727

### Short Description and Why It's Useful
When there is an import from "@vue-storefront", VS Code returns this error: "Cannot find module ...".

With this modification, the problem (described here: https://forum.vuestorefront.io/t/vs-code-and-typescript-imports/1244) is solved.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gibkigonzo** [comment]
@rozzilla Can you please check build errors?

**Comment by rozzilla** [comment]
Hi @gibkigonzo ,
my commit include only this change:
"@vue-storefront/*": ["./*"]

So I don't know what is wrong with that. In my case it solve the problem mentioned.

**Comment by rozzilla** [comment]
I've signed the CLA

**Comment by bloodf** [comment]
This is closed due to inactivity.

If you want your PR to be re-opened, please update your files, check for any conflicts.

If your PR is for Vue Storefront 1 target the new repository at https://github.com/vuestorefront/vue-storefront-1

**Pull request closed without merging**
